nyaa/views/site.py
import flask

bp = flask.Blueprint('site', __name__)


# @bp.route('/about', methods=['GET'])
# def about():
#     return flask.render_template('about.html')


@bp.route('/rules', methods=['GET'])
def rules():
    return flask.render_template('rules.html')


@bp.route('/help', methods=['GET'])
def help():
    return flask.render_template('help.html')


@bp.route('/xmlns/nyaa', methods=['GET'])
def xmlns_nyaa():
    return flask.render_template('xmlns.html')


@bp.route('/trusted', methods=['GET'])
def trusted():
    return flask.render_template('trusted.html')

nyaa/views/users.py
import binascii
import math
import time
from ipaddress import ip_address
from itertools import chain

import flask
from flask_paginate import Pagination

from itsdangerous import BadSignature, URLSafeSerializer

from nyaa import forms, models
from nyaa.extensions import db
from nyaa.search import (DEFAULT_MAX_SEARCH_RESULT, DEFAULT_PER_PAGE, SERACH_PAGINATE_DISPLAY_MSG,
                         _generate_query_string, search_db, search_db_baked, search_elastic)
from nyaa.utils import admin_only, chain_get, sha1_hash

app = flask.current_app
bp = flask.Blueprint('users', __name__)


@bp.route('/user/<user_name>', methods=['GET', 'POST'])
def view_user(user_name):
    user = models.User.by_username(user_name)

    if not user:
        flask.abort(404)

    admin_form = None
    ban_form = None
    bans = None
    ipbanned = None
    nuke_form = None
    if flask.g.user and flask.g.user.is_moderator and flask.g.user.level > user.level:
        admin_form = forms.UserForm()
        default, admin_form.user_class.choices = _create_user_class_choices(user)
        if flask.request.method == 'GET':
            admin_form.user_class.data = default

        ban_form = forms.BanForm()
        nuke_form = forms.NukeForm()
        if flask.request.method == 'POST':
            doban = (ban_form.ban_user.data or ban_form.unban.data or ban_form.ban_userip.data)
        bans = models.Ban.banned(user.id, user.last_login_ip).all()
        ipbanned = list(filter(lambda b: b.user_ip == user.last_login_ip, bans))

    url = flask.url_for('users.view_user', user_name=user.username)
    if flask.request.method == 'POST' and admin_form and not doban and admin_form.validate():
        selection = admin_form.user_class.data
        mapping = {'regular': models.UserLevelType.REGULAR,
                   'trusted': models.UserLevelType.TRUSTED,
                   'moderator': models.UserLevelType.MODERATOR}

        if mapping[selection] != user.level:
            user.level = mapping[selection]
            log = "[{}]({}) changed to {} user".format(user_name, url, selection)
            adminlog = models.AdminLog(log=log, admin_id=flask.g.user.id)
            db.session.add(adminlog)

        if admin_form.activate_user.data and not user.is_banned:
            if user.status != models.UserStatusType.ACTIVE:
                user.status = models.UserStatusType.ACTIVE
                adminlog = models.AdminLog("[{}]({}) was manually activated"
                                           .format(user_name, url), admin_id=flask.g.user.id)
                db.session.add(adminlog)
                flask.flash('{} was manually activated'.format(user_name), 'success')

        db.session.add(user)
        db.session.commit()

        return flask.redirect(url)

    if flask.request.method == 'POST' and ban_form and doban and ban_form.validate():
        if (ban_form.ban_user.data and user.is_banned) or \
                (ban_form.ban_userip.data and ipbanned) or \
                (ban_form.unban.data and not user.is_banned and not bans):
            flask.flash(flask.Markup('What the fuck are you doing?'), 'danger')
            return flask.redirect(url)

        user_str = "[{0}]({1})".format(user.username, url)

        if ban_form.unban.data:
            action = "unbanned"
            user.status = models.UserStatusType.ACTIVE
            db.session.add(user)

            for ban in bans:
                if ban.user_ip:
                    user_str += " IP({0})".format(ip_address(ban.user_ip))
                db.session.delete(ban)
        else:
            action = "banned"
            user.status = models.UserStatusType.BANNED
            db.session.add(user)

            ban = models.Ban(admin_id=flask.g.user.id, user_id=user.id, reason=ban_form.reason.data)
            db.session.add(ban)

            if ban_form.ban_userip.data:
                ban.user_ip = ip_address(user.last_login_ip)
                user_str += " IP({0})".format(ban.user_ip)
                ban.user_ip = ban.user_ip.packed

        log = "User {0} has been {1}.".format(user_str, action)
        adminlog = models.AdminLog(log=log, admin_id=flask.g.user.id)
        db.session.add(adminlog)

        db.session.commit()

        flask.flash(flask.Markup('User has been successfully {0}.'.format(action)), 'success')
        return flask.redirect(url)

    req_args = flask.request.args

    search_term = chain_get(req_args, 'q', 'term')

    sort_key = req_args.get('s')
    sort_order = req_args.get('o')

    category = chain_get(req_args, 'c', 'cats')
    quality_filter = chain_get(req_args, 'f', 'filter')

    page_number = chain_get(req_args, 'p', 'page', 'offset')
    try:
        page_number = max(1, int(page_number))
    except (ValueError, TypeError):
        page_number = 1

    results_per_page = app.config.get('RESULTS_PER_PAGE', DEFAULT_PER_PAGE)

    query_args = {
        'term': search_term or '',
        'user': user.id,
        'sort': sort_key or 'id',
        'order': sort_order or 'desc',
        'category': category or '0_0',
        'quality_filter': quality_filter or '0',
        'page': page_number,
        'rss': False,
        'per_page': results_per_page
    }

    if flask.g.user:
        query_args['logged_in_user'] = flask.g.user
        if flask.g.user.is_moderator:  # God mode
            query_args['admin'] = True

    # Use elastic search for term searching
    rss_query_string = _generate_query_string(search_term, category, quality_filter, user_name)
    use_elastic = app.config.get('USE_ELASTIC_SEARCH')
    if use_elastic and search_term:
        query_args['term'] = search_term

        max_search_results = app.config.get('ES_MAX_SEARCH_RESULT', DEFAULT_MAX_SEARCH_RESULT)

        # Only allow up to (max_search_results / page) pages
        max_page = min(query_args['page'], int(math.ceil(max_search_results / results_per_page)))

        query_args['page'] = max_page
        query_args['max_search_results'] = max_search_results

        query_results = search_elastic(**query_args)

        max_results = min(max_search_results, query_results['hits']['total'])
        # change p= argument to whatever you change page_parameter to or pagination breaks
        pagination = Pagination(p=query_args['page'], per_page=results_per_page,
                                total=max_results, bs_version=3, page_parameter='p',
                                display_msg=SERACH_PAGINATE_DISPLAY_MSG)
        return flask.render_template('user.html',
                                     use_elastic=True,
                                     pagination=pagination,
                                     torrent_query=query_results,
                                     search=query_args,
                                     user=user,
                                     user_page=True,
                                     rss_filter=rss_query_string,
                                     admin_form=admin_form,
                                     ban_form=ban_form,
                                     nuke_form=nuke_form,
                                     bans=bans,
                                     ipbanned=ipbanned)
    # Similar logic as home page
    else:
        if use_elastic:
            query_args['term'] = ''
        else:
            query_args['term'] = search_term or ''
        if app.config['USE_BAKED_SEARCH']:
            query = search_db_baked(**query_args)
        else:
            query = search_db(**query_args)
        return flask.render_template('user.html',
                                     use_elastic=False,
                                     torrent_query=query,
                                     search=query_args,
                                     user=user,
                                     user_page=True,
                                     rss_filter=rss_query_string,
                                     admin_form=admin_form,
                                     ban_form=ban_form,
                                     nuke_form=nuke_form,
                                     bans=bans,
                                     ipbanned=ipbanned)


@bp.route('/user/<user_name>/comments')
def view_user_comments(user_name):
    user = models.User.by_username(user_name)

    if not user:
        flask.abort(404)

    # Only moderators get to see all comments for now
    if not flask.g.user or not flask.g.user.is_moderator:
        flask.abort(403)

    page_number = flask.request.args.get('p')
    try:
        page_number = max(1, int(page_number))
    except (ValueError, TypeError):
        page_number = 1

    comments_per_page = 100

    comments_query = (models.Comment.query.filter(models.Comment.user == user)
                                          .order_by(models.Comment.created_time.desc()))
    comments_query = comments_query.paginate_faste(page_number, per_page=comments_per_page, step=5)
    return flask.render_template('user_comments.html',
                                 comments_query=comments_query,
                                 user=user)


@bp.route('/user/activate/<payload>')
def activate_user(payload):
    if app.config['MAINTENANCE_MODE']:
        flask.flash(flask.Markup('<strong>Activations are currently disabled.</strong>'), 'danger')
        return flask.redirect(flask.url_for('main.home'))

    s = get_serializer()
    try:
        user_id = s.loads(payload)
    except BadSignature:
        flask.abort(404)

    user = models.User.by_id(user_id)

    # Only allow activating inactive users
    if not user or user.status != models.UserStatusType.INACTIVE:
        flask.abort(404)

    # Set user active
    user.status = models.UserStatusType.ACTIVE
    db.session.add(user)
    db.session.commit()

    # Log user in
    flask.g.user = user
    flask.session['user_id'] = user.id
    flask.session.permanent = True
    flask.session.modified = True

nyaa/templates/_formhelpers.html
{% macro render_field(field, render_label=True) %}
{% if field.errors %}
	<div class="form-group has-error">
{% else %}
	<div class="form-group">
{% endif %}
		{% if render_label %}
		{{ field.label(class='control-label') }}
		{% endif %}
		{{ field(title=field.description,**kwargs) | safe }}
		{% if field.errors %}
			<div class="help-block">
				{% if field.errors|length < 2 %}
					{% for error in field.errors %}
						{{ error }}
					{% endfor %}
				{% else %}
					<ul>
						{% for error in field.errors %}
							<li>{{ error }}</li>
						{% endfor %}
					</ul>
				{% endif %}
			</div>
		{% endif %}
	</div>
{% endmacro %}


{% macro render_markdown_editor(field, field_name='') %}
{% if field.errors %}
	<div class="form-group has-error">
{% else %}
	<div class="form-group">
{% endif %}
	<div class="markdown-editor" id="{{ field_name }}-markdown-editor" data-field-name="{{ field_name }}">
		{{ field.label(class='control-label') }}
		<a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" class="small" target="_blank">Markdown supported</a>
		<ul class="nav nav-tabs" role="tablist">
			<li role="presentation" class="active">
				<a href="#{{ field_name }}-tab" role="tab" data-toggle="tab">
					Write
				</a>
			</li>
			<li role="presentation">
				<a href="#{{ field_name }}-preview" id="{{ field_name }}-preview-tab" role="tab" data-toggle="tab">
					Preview
				</a>
			</li>
		</ul>
		<div class="tab-content">
			<div role="tabpanel" class="tab-pane active" id="{{ field_name }}-tab" data-markdown-target="#{{ field_name }}-markdown-target">
				{# Render this field manually, because we need to escape the inner text #}
				<textarea class="form-control markdown-source" id="{{ field.id }}" name="{{ field.name }}">
				{{- (field.data or "") | escape | replace('\r\n', '\n') | replace('\n', '&#10;'|safe) -}}
				</textarea>
				{% if field.errors %}
					<div class="help-block">
						{% if field.errors|length < 2 %}
							{% for error in field.errors %}
								{{ error }}
							{% endfor %}
						{% else %}
							<ul>
								{% for error in field.errors %}
									<li>{{ error }}</li>
								{% endfor %}
							</ul>
						{% endif %}
					</div>
				{% endif %}
			</div>
			<div role="tabpanel" class="tab-pane" id="{{ field_name }}-preview">
				<div class="well" id="{{ field_name }}-markdown-target"></div>
			</div>
		</div>
	</div>
</div>
{% endmacro %}


{% macro render_upload(field) %}
{% if field.errors %}
	<div class="form-group has-error">
{% else %}
	<div class="form-group">
{% endif %}
		<label class="control-label" for="torrent_file">Torrent file</label>
		<div class="input-group">
			<label for="{{ field.id }}" class="input-group-btn">
				<span class="btn btn-default">Browse&hellip;</span>
			</label>
			<input type="text" class="form-control" readonly>
		</div>
		<div class="sr-only">
			{{ field(title=field.description,**kwargs) | safe }}
		</div>
		{% if field.errors %}
			<div class="help-block">
				{% if field.errors|length < 2 %}
					{% for error in field.errors %}
						{{ error }}
					{% endfor %}
				{% else %}
					<ul>
						{% for error in field.errors %}
							<li>{{ error }}</li>
						{% endfor %}
					</ul>
				{% endif %}
			</div>
		{% endif %}
	</div>
{% endmacro %}

{% macro render_menu_with_button(field, button_label='Apply') %}
{% if field.errors %}
	<div class="form-group has-error">
{% else %}
	<div class="form-group">
{% endif %}
		{{ field.label(class='control-label') }}
		<div class="input-group input-group-sm">
			{{ field(title=field.description, class_="form-control",**kwargs) | safe }}
			<div class="input-group-btn">
				<button type="submit" class="btn btn-primary">{{ button_label }}</button>
			</div>
		</div>
		{% if field.errors %}
			<div class="help-block">
				{% if field.errors|length < 2 %}
					{% for error in field.errors %}
						{{ error }}
					{% endfor %}
				{% else %}
					<ul>
						{% for error in field.errors %}
							<li>{{ error }}</li>
						{% endfor %}
					</ul>
				{% endif %}
			</div>
		{% endif %}
	</div>
{% endmacro %}

nyaa/templates/admin_trusted_view.html
{% extends "layout.html" %}
{% from "_formhelpers.html" import render_field, render_menu_with_button %}
{%- macro review_class(rec) -%}
{%- if rec.name == 'ACCEPT' -%}
{{ 'panel-success' -}}
{%- elif rec.name == 'REJECT' -%}
{{ 'panel-danger' -}}
{%- elif rec.name == 'ABSTAIN' -%}
{{ 'panel-default' -}}
{%- endif -%}
{%- endmacro -%}
{% block title %}{{ app.submitter.username }}'s Application :: {{ config.SITE_NAME }}{% endblock %}
{% block body %}
<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">{{ app.submitter.username }}'s Application</h3>
	</div>
	<div class="panel-body">
		<div class="row">
			<dl>
				<div class="col-xs-4 col-sm-2 col-md-2">
					<dt>Submitter</dt>
					<dd>
						<a href="{{ url_for('users.view_user', user_name=app.submitter.username) }}">
							{{ app.submitter.username }}
						</a>
					</dd>
				</div>
				<div class="col-xs-4 col-sm-2 col-md-2">
					<dt>Submitted on</dt>
					<dd data-timestamp="{{ app.created_utc_timestamp | int }}">
						{{ app.created_time.strftime('%Y-%m-%d %H:%M') }}
					</dd>
				</div>
				<div class="col-xs-4 col-sm-2 col-md-2">
					<dt>Status</dt>
					<dd>{{ app.status.name.capitalize() }}</dd>
				</div>
			</dl>
		</div>
		<hr>
		<div class="row">
			<div class="col-md-12">
				<h4>Why do you think you should be given trusted status?</h4>
				<div class="panel panel-default">
					<div class="panel-body" markdown-text markdown-no-images>
						{{- app.why_give | escape | replace('\r\n', '\n') | replace('\n', '&#10;'|safe) -}}
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<h4>Why do you want to become a trusted user?</h4>
				<div class="panel panel-default">
					<div class="panel-body" markdown-text markdown-no-images>
						{{- app.why_want | escape | replace('\r\n', '\n') | replace('\n', '&#10;'|safe) -}}
					</div>
				</div>
			</div>
		</div>
	</div>
	{%- if decision_form -%}
	<div class="panel-footer">
		<form method="POST">
			{{ decision_form.csrf_token }}
			<div class="btn-group" role="group" aria-label="Decision">
				{{ decision_form.reject(class="btn btn-danger") }}
				{{ decision_form.accept(class="btn btn-success") }}
			</div>
		</form>
	</div>
	{%- endif -%}
</div>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Reviews - {{ app.reviews | length }}</h3>
	</div>
	<div class="panel-body">
		{% for rev in app.reviews %}
		<div class="panel {{ review_class(rev.recommendation) -}}">
			<div class="panel-heading">
				<h3 class="panel-title">{{ rev.reviewer.username }}'s Review</h3>
			</div>
			<div class="panel-body">
				<div markdown-text>
					{{- rev.comment | escape | replace('\r\n', '\n') | replace('\n', '&#10;'|safe) -}}
				</div>
			</div>
			<div class="panel-footer">
				{%- if rev.recommendation.name == 'ABSTAIN' -%}
				{{ rev.reviewer.username }} does not give an explicit recommendation.
				{%- else -%}
				{{ rev.reviewer.username }} recommends to <strong>{{ rev.recommendation.name.lower() }}</strong> this application.
				{%- endif -%}
			</div>
		</div>
		{% endfor %}
		<form method="POST">
			{{ review_form.csrf_token }}
			<div class="row">
				<div class="col-xs-12 col-md-8 col-sm-10">
					{{ render_field(review_form.comment, class_="form-control") }}
				</div>
			</div>
			<div class="row">
				<div class="col-xs-3">
					{{ render_menu_with_button(review_form.recommendation, 'Submit') }}
				</div>
			</div>
		</form>
	</div>
</div>
{% endblock %}

nyaa/templates/infobubble.html
{# Update this to a larger timestamp if you change your announcement #}
{# A value of 0 disables the announcements altogether #}
{% set info_ts = 0 %}
{% if info_ts > 0 %}
<div class="alert alert-info alert-dismissible" id="infobubble" data-ts='{{ info_ts }}' hidden>
	{% include 'infobubble_content.html' %}
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	</button>
</div>
<noscript>
<div class="alert alert-info" id="infobubble-noscript">
	{% include 'infobubble_content.html' %}
</div>
</noscript>
{% endif %}

nyaa/templates/login.html
{% extends "layout.html" %}
{% block title %}Login :: {{ config.SITE_NAME }}{% endblock %}
{% block metatags %}
<meta property="og:description" content="Log in to {{ config.SITE_NAME }}!">
{% endblock %}
{% block body %}
{% from "_formhelpers.html" import render_field %}

<h1>Login</h1>
	<form method="POST">
		{{ form.csrf_token }}

		<div class="row">
			<div class="form-group col-md-4">
				{{ render_field(form.username, class_='form-control', placeholder='Username', autofocus='', tabindex='1') }}
			</div>
		</div>

		<div class="row">
			<div class="form-group col-md-4">
				{# This is just render_field() exploded so that we can add the password link after the label #}
				{% if form.password.errors %}
					<div class="form-group has-error">
				{% else %}
					<div class="form-group">
				{% endif %}
						{{ form.password.label(class='control-label') }}

						{% if config.ALLOW_PASSWORD_RESET: %}
						<small>
							<a href="{{ url_for('account.password_reset') }}">Forgot your password?</a>
						</small>
						{% endif%}

						{{ form.password(title=form.password.description, class_='form-control', tabindex='2') | safe }}
						{% if form.password.errors %}
							<div class="help-block">
								{% if form.password.errors|length < 2 %}
									{% for error in form.password.errors %}
										{{ error }}
									{% endfor %}
								{% else %}
									<ul>
										{% for error in form.password.errors %}
											<li>{{ error }}</li>
										{% endfor %}
									</ul>
								{% endif %}
							</div>
						{% endif %}
					</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-4">
				<input type="submit" value="Login" class="btn btn-primary" tabindex="3">
			</div>
		</div>
	</form>
{% endblock %}

nyaa/templates/trusted.html
{% extends "layout.html" %}
{% block title %}Trusted :: {{ config.SITE_NAME }}{% endblock %}
{% block body %}

<div class="content">
	<div class="row">
		<div class="col-md-12">
			{% include "trusted_rules.html" %}
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<a href="{{ url_for('account.request_trusted') }}" class="btn btn-success btn-lg">Request Trusted Status</a>
		</div>
	</div>
</div>
{% endblock %}

nyaa/templates/trusted_form.html
{% extends "layout.html" %}
{% from "_formhelpers.html" import render_field %}
{% block title %}Apply for Trusted :: {{ config.SITE_NAME }}{% endblock %}
{% block body %}
<div class="content">
	{% if trusted_form %}
	<div class="row">
		<div class="col-md-12">
			<h1>You are eligible to apply for trusted status</h1>
		</div>
	</div>
	<form class="trusted-form" method="POST">
		{{ trusted_form.csrf_token }}
		<div class="row">
			<div class="col-md-6">
				{{ render_field(trusted_form.why_give_trusted, class_='form-control') }}
			</div>
		</div>
		<div class="row">
			<div class="col-md-6">
				{{ render_field(trusted_form.why_want_trusted, class_='form-control') }}
			</div>
		</div>
		<div class="row">
			<div class="col-md-2">
				<input type="submit" value="Submit" class="btn btn-success btn-sm">
			</div>
		</div>
	</form>
	{% else %}
	<div class="row">
		<div class="col-md-12">
			<h1>You are currently not eligible to apply for trusted status</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<p>
				You currently are not eligible to apply for trusted status for the following
				reason{% if deny_reasons|length > 1 %}s{% endif %}:
			</p>
			<ul>
				{% for reason in deny_reasons %}
				<li>{{ reason }}</li>
				{% endfor %}
			</ul>
		</div>
	</div>
	{% endif %}
</div>
{% endblock %}

nyaa/templates/trusted_rules.html
<h1>Trusted rules go here</h1>

nyaa/templates/user.html
{% extends "layout.html" %}
{% block title %}{{ user.username }} :: {{ config.SITE_NAME }}{% endblock %}
{% block meta_image %}{{ user.gravatar_url() }}{% endblock %}
{% block metatags %}
{% if search.term %}
<meta property="og:description" content="Search for '{{ search.term }}' in torrents uploaded by {{ user.username }}">
{% else %}
<meta property="og:description" content="Torrents uploaded by {{ user.username }}">
{% endif %}
{% endblock %}

{% block body %}
{% from "_formhelpers.html" import render_menu_with_button %}
{% from "_formhelpers.html" import render_field %}

{% if g.user and g.user.is_moderator %}
	<h2>User Information</h2><br>
	<div class="row" style="margin-bottom: 20px;">
		<div class="col-md-2" style="max-width: 150px;">
			<img class="avatar" src="{{ user.gravatar_url() }}">
			<a href="{{ url_for('users.view_user_comments', user_name=user.username) }}">View all comments</a>
		</div>
		<div class="col-md-4">
			<div class="row">
				<div class="col-md-12">
					<dl class="dl-horizontal">
						<dt>User ID:</dt>
						<dd>{{ user.id }}</dd>
						<dt>Account created on:</dt>
						<dd data-timestamp="{{ user.created_utc_timestamp|int }}">{{ user.created_time.strftime('%Y-%m-%d %H:%M UTC') }}</dd>
						<dt>Email address:</dt>
						<dd>{{ user.email }}</dd>
						<dt>User class:</dt>
						<dd>{{ user.userlevel_str }}</dd>
						<dt>User status:</dt>
						<dd>{{ user.userstatus_str }}</dt>
						{%- if g.user.is_superadmin -%}
						<dt>Last login IP:</dt>
						<dd>{{ user.ip_string }}</dd>
						<dt>Registration IP:</dt>
						<dd>{{ user.reg_ip_string }}</dd>
						{%- endif -%}
					</dl>
				</div>
			</div>
			{% if admin_form %}
			<form method="POST">
				{{ admin_form.csrf_token }}
				<div class="row">
					<div class="col-md-6">
						{{ render_menu_with_button(admin_form.user_class) }}
					</div>
				</div>
				{% if not user.is_active %}
				<div class="row">
					<div class="col-md-6">
						{{ admin_form.activate_user(class="btn btn-primary") }}
					</div>
				</div>
				{% endif %}
			</form>
			<br>
			{% endif %}
		</div>
		{% if ban_form %}
		<div class="col-md-5">
			<div class="panel panel-danger">
				<div class="panel-heading">
					<h3 class="panel-title">Danger Zone</h3>
				</div>
				<div class="panel-body">
					<form method="POST">
						<div class="row">
							<div class="col-md-12">
								{{ ban_form.csrf_token }}
								{% if user.is_banned %}
								This user is <strong>banned</strong>.
								{% endif %}
								{% if ipbanned %}
								This user is <strong>ip banned</strong>.
								{% endif %}
								{% if not user.is_banned and not bans %}
								This user is <strong>not banned</strong>.
								{% endif %}
							</div>
						</div>
						{% if user.is_banned or bans %}
						<div class="row">
							<div class="col-md-12">
								<ul>
									{% for ban in bans %}
									<li>#{{ ban.id }}
									by <a href="{{ url_for('users.view_user', user_name=ban.admin.username) }}">{{ ban.admin.username }}</a>
									for <span markdown-text-inline>{{ ban.reason }}</span></li>
									{% endfor %}
								</ul>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								{{ ban_form.unban(class="btn btn-info") }}
							</div>
						</div>
						{% endif %}

						{% if not user.is_banned or not ipbanned %}
						{% if user.is_banned or bans %}
						<hr>
						{% endif %}
						<div class="row" style="margin-top:1.5em">
							<div class="col-md-12">
								{{ render_field(ban_form.reason, class_="form-control", placeholder="Specify a ban reason.") }}<br>
							</div>
						</div>
						<div class="row">
							<div class="col-md-6 text-left">
								{% if not user.is_banned %}
								{{ ban_form.ban_user(value="Ban User", class="btn btn-danger") }}
								{% else %}
								<button type="button" class="btn btn-danger disabled">Already banned</button>
								{% endif %}
							</div>
							<div class="col-md-6 text-right">
								{% if not ipbanned %}
								{{ ban_form.ban_userip(value="Ban User+IP", class="btn btn-danger") }}
								{% else %}
								<button type="button" class="btn btn-danger disabled">Already IP banned</button>
								{% endif %}
							</div>
						</div>
						{% endif %}
					</form>
					{% if g.user.is_superadmin %}
					<hr>
					<form method="POST" onsubmit="return prompt('Please type {{ user.username }} to confirm') == '{{ user.username }}'">
						{{ nuke_form.csrf_token }}
						<div class="row">
							<div class="col-md-6 text-left">
								{{ nuke_form.nuke_torrents(class="btn btn-danger", formaction=url_for('users.nuke_user_torrents', user_name=user.username)) }}
							</div>
							<div class="col-md-6 text-right">
								{{ nuke_form.nuke_comments(class="btn btn-danger", formaction=url_for('users.nuke_user_comments', user_name=user.username)) }}
							</div>
						</div>
					</form>
					{% endif %}
				</div>
			</div>
		</div>
		{% endif %}
	</div>
{% endif %}

<div class="row">
	<h3>
		Browsing <span class="text-{{ user.userlevel_color }}" data-toggle="tooltip" title="{{ user.userlevel_str }}">{{ user.username }}</span>'{{ '' if user.username[-1] == 's' else 's' }} torrents
		{% if torrent_query.actual_count is number and not search.term: %}
		 ({{ torrent_query.actual_count  }})
		{% endif %}
	</h3>

{% include "search_results.html" %}

{% endblock %}
</div>